name: BUILD

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时检查一次
  workflow_dispatch:     # 允许手动触发
    inputs:
      tag:
        description: 'Version tag to build'
        required: true
        type: string

jobs:
  schedule_trigger:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Get latest release from origin
        id: origin_release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: eclipse-theia
          repo: theia-ide
          excludes: prerelease, draft

      - name: Check if existed in thie repo
        id: check_release
        uses: joutvhu/get-release@v1
        with:
          tag_name: ${{ steps.origin_release.outputs.release }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Save info
        id: save_info
        run: |
            schedule_trigger=${{ steps.check_release.outputs.tag_name }}
            if [ -z "$schedule_trigger" ];then
              echo "New release detected!"
              echo "tag=${{ steps.origin_release.outputs.release }}" >> $GITHUB_OUTPUT
            else
              echo "No new release"
            fi
    outputs:
      tag: ${{ steps.save_info.outputs.tag }}

  manual_trigger:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Save info
        id: save_info
        run: |
            echo "Force trigger new build!"
            echo "Tag: ${{ github.event.inputs.tag }}"
            echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT

    outputs:
      tag: ${{ steps.save_info.outputs.tag }}

  build_trigger:
    needs: [schedule_trigger, manual_trigger] # 检查两个trigger的情况
    if: always() # 保持运行防止依赖跳过导致本任务不执行
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Save info
        id: save_info
        # 定时触发，只有tag不存在才进行
        run: |
            echo "Check trigger and tag"

            schedule_trigger=${{ needs.schedule_trigger.outputs.tag }}
            manual_trigger=${{ needs.manual_trigger.outputs.tag }}

            # -z check if empty
            if [[ -z "$schedule_trigger" ]];then
              echo "New tag detected from dispatch"
              echo "tag=$manual_trigger" >> $GITHUB_OUTPUT
            elif [[ -z "$manual_trigger" ]] ;then
              echo "New tag detected from schedule"
              echo "tag=$schedule_trigger" >> $GITHUB_OUTPUT
            else
              echo "No new release"
            fi
    outputs:
      tag: ${{ steps.save_info.outputs.tag }}

  build_thiea: # 跳过似乎会向下传导，不加always, 两个trigger之一被跳过就会不执行build
    needs: [build_trigger]
    if:  ${{ always() && (needs.build_trigger.outputs.tag != ''  || needs.build_trigger.outputs.tag != null) }}
    permissions:
      contents: write
    runs-on: ubuntu-22.04-arm
    steps:

      - name: Checkout Specific Tag
        uses: actions/checkout@v4
        with:
          ref:  ${{ needs.build_trigger.outputs.tag }}  # 指定要检出的 tag 名称
          path: theia-ide
          fetch-depth: 0  # 确保获取完整的仓库历史记录（可选）

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0

      - name: Build Theia Browser
        working-directory: theia-ide
        shell: bash
        run: |
          yarn build:extensions
          yarn download:plugins
          yarn browser build
          yarn

      - name: Compress output
        working-directory: theia-ide/applications
        run: |
          7zz -tzip a browser.zip browser

      - name: Release
        uses: ncipollo/release-action@v1.15.0
        with:
          draft: false
          generateReleaseNotes: true  #自动生成发行说明。
          owner: "SilenWang"
          repo: "theia-ide-browser-build"
          artifacts: '${{ github.workspace }}/theia-ide/applications/*.zip'
          removeArtifacts: true
          replacesArtifacts: true
          allowUpdates: true
          tag: ${{ needs.build_trigger.outputs.tag }}
          name: Release for Thiea-IDE browser ${{ needs.build_trigger.outputs.tag }}